import type {
  Category,
  City,
  ContractorProfile,
  ContractorType,
  Country,
  EquipmentProfile,
  EquipmentType,
  MaterialProfile,
  BusinessOpportunity,
  ProjectTenderProfile,
  ProjectTenderType,
} from "@/lib/types";

export const categories: Category[] = [
  {
    slug: "contractors",
    name: "Contractors",
    description:
      "Pre-qualified contractors for civil, MEP, infrastructure, and fit-out projects.",
    icon: "🏗️",
    listingCount: 2458,
  },
  {
    slug: "projects-tenders",
    name: "Projects & Tenders",
    description:
      "Live GCC opportunities, tenders, and public procurement listings.",
    icon: "📋",
    listingCount: 1892,
  },
  {
    slug: "business-opportunities",
    name: "Business Opportunities",
    description: "Trade leads, partnership requests, and growth opportunities.",
    icon: "💼",
    listingCount: 1756,
  },
  {
    slug: "equipment-marketplace",
    name: "Equipment Marketplace",
    description:
      "Heavy equipment, rentals, spare parts, and machinery sourcing.",
    icon: "🚜",
    listingCount: 3215,
  },
  {
    slug: "warehouses",
    name: "Warehouses",
    description:
      "Industrial storage, logistics, and distribution warehouse providers.",
    icon: "📦",
    listingCount: 1256,
  },
  {
    slug: "labour-camps",
    name: "Labour Camps",
    description:
      "Worker accommodation and camp management services across the Gulf.",
    icon: "🏕️",
    listingCount: 892,
  },
  {
    slug: "construction-materials",
    name: "Construction & Industrial Materials",
    description:
      "Concrete, steel, piping, HVAC, and industrial material suppliers.",
    icon: "🧱",
    listingCount: 2754,
  },
];

export const contractorTypes: ContractorType[] = [
  { slug: "civil-contractors", name: "Civil Contractors" },
  { slug: "building-contractors", name: "Building Contractors" },
  { slug: "infrastructure-contractors", name: "Infrastructure Contractors" },
  { slug: "road-contractors", name: "Road Contractors" },
  { slug: "mep-contractors", name: "MEP Contractors" },
  { slug: "electrical-contractors", name: "Electrical Contractors" },
  { slug: "plumbing-contractors", name: "Plumbing Contractors" },
  { slug: "hvac-contractors", name: "HVAC Contractors" },
  {
    slug: "interior-fit-out-contractors",
    name: "Interior Fit-Out Contractors",
  },
  { slug: "steel-fabrication", name: "Steel Fabrication" },
  { slug: "industrial-maintenance", name: "Industrial Maintenance" },
  { slug: "epc-contractors", name: "EPC Contractors" },
  { slug: "oil-gas-contractors", name: "Oil & Gas Contractors" },
  { slug: "engineering-consultants", name: "Engineering Consultants" },
  { slug: "quantity-surveyors", name: "Quantity Surveyors" },
  { slug: "bim-consultants", name: "BIM Consultants" },
  { slug: "cost-estimation-services", name: "Cost Estimation Services" },
];

export const projectTenderTypes: ProjectTenderType[] = [
  { slug: "building-projects", name: "Building Projects" },
  { slug: "infrastructure-projects", name: "Infrastructure Projects" },
  { slug: "government-tenders", name: "Government Tenders" },
  { slug: "industrial-projects", name: "Industrial Projects" },
  { slug: "oil-gas-projects", name: "Oil & Gas Projects" },
  { slug: "mep-projects", name: "MEP Projects" },
  { slug: "interior-fit-out", name: "Interior Fit-Out" },
  { slug: "roads-bridges", name: "Roads & Bridges" },
  { slug: "factory-projects", name: "Factory Projects" },
  { slug: "warehouse-construction", name: "Warehouse Construction" },
  { slug: "maintenance-contracts", name: "Maintenance Contracts" },
];

export const equipmentTypes: EquipmentType[] = [
  { slug: "excavators", name: "Excavators" },
  { slug: "cranes", name: "Cranes" },
  { slug: "forklifts", name: "Forklifts" },
  { slug: "boom-lifts", name: "Boom Lifts" },
  { slug: "loaders", name: "Loaders" },
  { slug: "trucks", name: "Trucks" },
  { slug: "rollers", name: "Rollers" },
  { slug: "scaffolding", name: "Scaffolding" },
  { slug: "generators", name: "Generators" },
  { slug: "compressors", name: "Compressors" },
];

export const countries: Country[] = [
  { code: "AE", name: "UAE" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "KW", name: "Kuwait" },
  { code: "QA", name: "Qatar" },
  { code: "OM", name: "Oman" },
  { code: "BH", name: "Bahrain" },
];

export const cities: City[] = [
  { slug: "dubai", name: "Dubai", countryCode: "AE" },
  { slug: "abu-dhabi", name: "Abu Dhabi", countryCode: "AE" },
  { slug: "riyadh", name: "Riyadh", countryCode: "SA" },
  { slug: "jeddah", name: "Jeddah", countryCode: "SA" },
  { slug: "doha", name: "Doha", countryCode: "QA" },
  { slug: "muscat", name: "Muscat", countryCode: "OM" },
  { slug: "manama", name: "Manama", countryCode: "BH" },
  { slug: "kuwait-city", name: "Kuwait City", countryCode: "KW" },
];

export const equipmentListings: EquipmentProfile[] = [
  {
    slug: "cat-320-gc-excavator",
    title: "CAT 320 GC Hydraulic Excavator",
    equipmentType: "Excavators",
    equipmentTypeSlug: "excavators",
    listingType: "For Sale",
    condition: "Excellent",
    country: "UAE",
    countryCode: "AE",
    city: "Dubai",
    citySlug: "dubai",
    brand: "Caterpillar",
    model: "320 GC",
    year: 2022,
    operatingHours: 2840,
    price: "AED 365,000",
    priceNote: "Ex-yard, excluding VAT",
    availability: "Ready for inspection",
    location: "Dubai Industrial City, Dubai",
    description:
      "GCC-spec hydraulic excavator maintained under a dealer service plan. Clean undercarriage, cold air conditioning, and complete maintenance history.",
    specifications: [
      { label: "Operating weight", value: "21,900 kg" },
      { label: "Engine power", value: "146 hp" },
      { label: "Bucket capacity", value: "1.0 m³" },
      { label: "Maximum digging depth", value: "6.7 m" },
    ],
    sellerName: "Gulf Heavy Machines LLC",
    sellerType: "Verified equipment dealer",
    phone: "+971 4 555 0182",
    whatsapp: "+971 50 555 0182",
    email: "sales@gulfheavymachines.example",
    verified: true,
    featured: true,
    images: [],
    posted: "2 days ago",
  },
  {
    slug: "liebherr-ltm-1100-mobile-crane",
    title: "Liebherr LTM 1100 Mobile Crane",
    equipmentType: "Cranes",
    equipmentTypeSlug: "cranes",
    listingType: "For Rent",
    condition: "Excellent",
    country: "Saudi Arabia",
    countryCode: "SA",
    city: "Riyadh",
    citySlug: "riyadh",
    brand: "Liebherr",
    model: "LTM 1100-4.2",
    year: 2021,
    operatingHours: 3900,
    price: "SAR 3,800 / day",
    priceNote: "Operator and standard rigging included",
    availability: "Available from 05 Aug 2026",
    location: "Second Industrial City, Riyadh",
    description:
      "100-ton all-terrain mobile crane available with certified operator, lifting accessories, and current third-party inspection.",
    specifications: [
      { label: "Maximum capacity", value: "100 t" },
      { label: "Telescopic boom", value: "60 m" },
      { label: "Axles", value: "4" },
      { label: "Drive", value: "8 × 6 × 8" },
    ],
    sellerName: "Najd Lifting Solutions",
    sellerType: "Verified rental company",
    phone: "+966 11 555 0410",
    whatsapp: "+966 55 555 0410",
    email: "hire@najdlifting.example",
    verified: true,
    featured: true,
    images: [],
    posted: "Today",
  },
  {
    slug: "toyota-8fd30-forklift",
    title: "Toyota 8FD30 Diesel Forklift",
    equipmentType: "Forklifts",
    equipmentTypeSlug: "forklifts",
    listingType: "For Sale",
    condition: "Good",
    country: "Qatar",
    countryCode: "QA",
    city: "Doha",
    citySlug: "doha",
    brand: "Toyota",
    model: "8FD30",
    year: 2019,
    operatingHours: 6120,
    price: "QAR 78,000",
    priceNote: "Negotiable after inspection",
    availability: "Available now",
    location: "Industrial Area, Doha",
    description:
      "Reliable 3-ton diesel forklift with side shift, solid tyres, and recently serviced mast assembly.",
    specifications: [
      { label: "Rated capacity", value: "3,000 kg" },
      { label: "Lift height", value: "4.5 m" },
      { label: "Fuel", value: "Diesel" },
      { label: "Mast", value: "Triplex" },
    ],
    sellerName: "Doha Material Handling",
    sellerType: "Equipment dealer",
    phone: "+974 4455 2090",
    whatsapp: "+974 3355 2090",
    email: "equipment@dmh.example",
    verified: true,
    featured: false,
    images: [],
    posted: "4 days ago",
  },
  {
    slug: "genie-s65-boom-lift",
    title: "Genie S-65 Telescopic Boom Lift",
    equipmentType: "Boom Lifts",
    equipmentTypeSlug: "boom-lifts",
    listingType: "For Rent",
    condition: "Good",
    country: "UAE",
    countryCode: "AE",
    city: "Abu Dhabi",
    citySlug: "abu-dhabi",
    brand: "Genie",
    model: "S-65",
    year: 2020,
    operatingHours: 3550,
    price: "AED 9,500 / month",
    priceNote: "Delivery charged by location",
    availability: "Available now",
    location: "Mussafah, Abu Dhabi",
    description:
      "Diesel telescopic boom lift suitable for steel erection, façade, and MEP access work.",
    specifications: [
      { label: "Working height", value: "21.8 m" },
      { label: "Horizontal reach", value: "17.1 m" },
      { label: "Platform capacity", value: "227 kg" },
      { label: "Drive", value: "4WD" },
    ],
    sellerName: "Access Gulf Rentals",
    sellerType: "Verified rental company",
    phone: "+971 2 555 7731",
    whatsapp: "+971 56 555 7731",
    email: "rentals@accessgulf.example",
    verified: true,
    featured: false,
    images: [],
    posted: "1 day ago",
  },
  {
    slug: "wanted-komatsu-wheel-loader",
    title: "Wanted: Komatsu WA470 Wheel Loader",
    equipmentType: "Loaders",
    equipmentTypeSlug: "loaders",
    listingType: "Wanted",
    condition: "Used",
    country: "Oman",
    countryCode: "OM",
    city: "Muscat",
    citySlug: "muscat",
    brand: "Komatsu",
    model: "WA470",
    year: 2018,
    operatingHours: null,
    price: "Budget: OMR 48,000",
    priceNote: "Depending on year and hours",
    availability: "Required within 30 days",
    location: "Muscat, Oman",
    description:
      "Buyer seeking a GCC-spec Komatsu WA470 or equivalent wheel loader with service records and sound drivetrain.",
    specifications: [
      { label: "Preferred year", value: "2018 or newer" },
      { label: "Maximum hours", value: "8,000 h" },
      { label: "Bucket", value: "3.8–4.2 m³" },
      { label: "Inspection", value: "Required before purchase" },
    ],
    sellerName: "Al Batinah Earthworks",
    sellerType: "Verified buyer",
    phone: "+968 2455 1880",
    whatsapp: "+968 9555 1880",
    email: "procurement@batinahearthworks.example",
    verified: true,
    featured: false,
    images: [],
    posted: "3 days ago",
  },
  {
    slug: "mercedes-actros-tipper",
    title: "Mercedes-Benz Actros 4140 Tipper",
    equipmentType: "Trucks",
    equipmentTypeSlug: "trucks",
    listingType: "For Sale",
    condition: "Good",
    country: "Kuwait",
    countryCode: "KW",
    city: "Kuwait City",
    citySlug: "kuwait-city",
    brand: "Mercedes-Benz",
    model: "Actros 4140",
    year: 2020,
    operatingHours: null,
    price: "KWD 28,500",
    priceNote: "Mileage: 186,000 km",
    availability: "Available now",
    location: "Shuwaikh Industrial Area, Kuwait City",
    description:
      "8×4 construction tipper with 20 m³ steel body, fleet maintained and ready for registration transfer.",
    specifications: [
      { label: "Configuration", value: "8 × 4" },
      { label: "Engine output", value: "400 hp" },
      { label: "Body capacity", value: "20 m³" },
      { label: "Mileage", value: "186,000 km" },
    ],
    sellerName: "Kuwait Fleet Trading",
    sellerType: "Commercial vehicle dealer",
    phone: "+965 2455 9002",
    whatsapp: "+965 6555 9002",
    email: "sales@kuwaitfleet.example",
    verified: false,
    featured: false,
    images: [],
    posted: "6 days ago",
  },
  {
    slug: "bomag-bw211-road-roller",
    title: "BOMAG BW 211 D-5 Soil Compactor",
    equipmentType: "Rollers",
    equipmentTypeSlug: "rollers",
    listingType: "For Rent",
    condition: "Excellent",
    country: "Bahrain",
    countryCode: "BH",
    city: "Manama",
    citySlug: "manama",
    brand: "BOMAG",
    model: "BW 211 D-5",
    year: 2022,
    operatingHours: 1780,
    price: "BHD 1,950 / month",
    priceNote: "Minimum one-month hire",
    availability: "Available now",
    location: "Sitra Industrial Area, Bahrain",
    description:
      "Single-drum soil compactor with smooth drum, air-conditioned cab, and valid safety certification.",
    specifications: [
      { label: "Operating weight", value: "10,700 kg" },
      { label: "Drum width", value: "2,130 mm" },
      { label: "Engine power", value: "128 hp" },
      { label: "Vibration", value: "2 amplitudes" },
    ],
    sellerName: "Bahrain Plant Hire",
    sellerType: "Rental company",
    phone: "+973 1755 0875",
    whatsapp: "+973 3655 0875",
    email: "hire@bahrainplant.example",
    verified: true,
    featured: false,
    images: [],
    posted: "Yesterday",
  },
  {
    slug: "ringlock-scaffolding-package",
    title: "Ringlock Scaffolding Package — 5,000 m²",
    equipmentType: "Scaffolding",
    equipmentTypeSlug: "scaffolding",
    listingType: "For Sale",
    condition: "New",
    country: "UAE",
    countryCode: "AE",
    city: "Dubai",
    citySlug: "dubai",
    brand: "GulfForm",
    model: "GF-Ringlock",
    year: 2026,
    operatingHours: null,
    price: "AED 410,000",
    priceNote: "Complete package with accessories",
    availability: "In stock",
    location: "Jebel Ali, Dubai",
    description:
      "Hot-dip galvanized ringlock scaffolding package supplied with standards, ledgers, decks, braces, base jacks, and access ladders.",
    specifications: [
      { label: "Coverage", value: "5,000 m²" },
      { label: "Finish", value: "Hot-dip galvanized" },
      { label: "Standard", value: "EN 12810 / EN 12811" },
      { label: "Delivery", value: "7–10 working days" },
    ],
    sellerName: "GulfForm Systems FZE",
    sellerType: "Verified manufacturer",
    phone: "+971 4 555 7100",
    whatsapp: "+971 52 555 7100",
    email: "sales@gulfform.example",
    verified: true,
    featured: true,
    images: [],
    posted: "Today",
  },
  {
    slug: "cummins-c500-generator",
    title: "Cummins C500D5 Diesel Generator",
    equipmentType: "Generators",
    equipmentTypeSlug: "generators",
    listingType: "For Rent",
    condition: "Excellent",
    country: "Saudi Arabia",
    countryCode: "SA",
    city: "Jeddah",
    citySlug: "jeddah",
    brand: "Cummins",
    model: "C500D5",
    year: 2023,
    operatingHours: 920,
    price: "SAR 18,000 / month",
    priceNote: "Fuel excluded; cables included",
    availability: "Available now",
    location: "Al Khumrah, Jeddah",
    description:
      "Silent-type 500 kVA generator for construction sites and temporary industrial power, supplied with distribution accessories.",
    specifications: [
      { label: "Standby power", value: "500 kVA" },
      { label: "Frequency", value: "50 Hz" },
      { label: "Voltage", value: "400 / 230 V" },
      { label: "Fuel tank", value: "990 L" },
    ],
    sellerName: "Red Sea Temporary Power",
    sellerType: "Verified rental company",
    phone: "+966 12 555 3900",
    whatsapp: "+966 54 555 3900",
    email: "power@redsearentals.example",
    verified: true,
    featured: false,
    images: [],
    posted: "2 days ago",
  },
  {
    slug: "atlas-copco-xas-88-compressor",
    title: "Atlas Copco XAS 88 Air Compressor",
    equipmentType: "Compressors",
    equipmentTypeSlug: "compressors",
    listingType: "Wanted",
    condition: "Good",
    country: "Qatar",
    countryCode: "QA",
    city: "Doha",
    citySlug: "doha",
    brand: "Atlas Copco",
    model: "XAS 88",
    year: 2020,
    operatingHours: null,
    price: "Budget: QAR 62,000",
    priceNote: "Open to equivalent 7-bar models",
    availability: "Required urgently",
    location: "Doha, Qatar",
    description:
      "Contractor seeking a towable air compressor in serviceable condition for pipeline and civil works.",
    specifications: [
      { label: "Free air delivery", value: "5.0 m³/min" },
      { label: "Working pressure", value: "7 bar" },
      { label: "Preferred hours", value: "Below 5,000 h" },
      { label: "Documentation", value: "Service records required" },
    ],
    sellerName: "Qatar Utility Contractors",
    sellerType: "Verified buyer",
    phone: "+974 4455 6810",
    whatsapp: "+974 6655 6810",
    email: "buying@qatarutility.example",
    verified: true,
    featured: false,
    images: [],
    posted: "5 hours ago",
  },
];

export const constructionMaterialTypes = [
  { slug: "cement-concrete", name: "Cement & Concrete" },
  { slug: "structural-steel", name: "Structural Steel" },
  { slug: "blocks-masonry", name: "Blocks & Masonry" },
  { slug: "waterproofing", name: "Waterproofing" },
  { slug: "finishing-materials", name: "Finishing Materials" },
];

export const industrialMaterialTypes = [
  { slug: "pipes-valves", name: "Pipes & Valves" },
  { slug: "electrical-supplies", name: "Electrical Supplies" },
  { slug: "hvac-components", name: "HVAC Components" },
  { slug: "industrial-chemicals", name: "Industrial Chemicals" },
  { slug: "safety-products", name: "Safety Products" },
];

export const materialListings: MaterialProfile[] = [
  {
    slug: "cem-i-portland-cement",
    name: "CEM I Portland Cement — Bulk & Bagged",
    materialGroup: "Construction Materials",
    materialType: "Cement & Concrete",
    materialTypeSlug: "cement-concrete",
    listingType: "Supplier",
    country: "Saudi Arabia",
    countryCode: "SA",
    city: "Riyadh",
    citySlug: "riyadh",
    supplier: "Yamama Cement Company",
    priceRange: "SAR 180–220 / Ton",
    minimumOrder: "50 Tons",
    availability: "In stock",
    leadTime: "3–5 working days",
    compliance: ["ASTM C150", "EN 197-1", "ISO 9001"],
    description: "Factory-direct CEM I 42.5N, CEM II, and sulfate-resistant cement for major building and infrastructure projects. Bulk tanker and bagged delivery available across Saudi Arabia.",
    specifications: [{ label: "Grade", value: "42.5N" }, { label: "Packaging", value: "50 kg bags / bulk" }, { label: "Origin", value: "Saudi Arabia" }, { label: "Shelf life", value: "6 months" }],
    phone: "+966 50 123 4567", whatsapp: "+966 50 123 4567",
    email: "sales@yamama-materials.example", verified: true,
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=1200&q=85",
    posted: "2 days ago",
  },
  {
    slug: "structural-steel-beams",
    name: "Structural Steel H-Beams & I-Beams",
    materialGroup: "Construction Materials", materialType: "Structural Steel",
    materialTypeSlug: "structural-steel", listingType: "For Sale",
    country: "Qatar", countryCode: "QA", city: "Doha", citySlug: "doha",
    supplier: "Qatar Steel Trading", priceRange: "QAR 2,400–2,650 / Ton",
    minimumOrder: "20 Tons", availability: "Ready stock", leadTime: "2–4 working days",
    compliance: ["ASTM A36", "EN 10025", "Mill Test Certificate"],
    description: "High-tensile structural steel sections, universal columns, channels, and angle bars with mill certificates and project-site delivery.",
    specifications: [{ label: "Grades", value: "S275 / S355" }, { label: "Lengths", value: "6–12 m" }, { label: "Finish", value: "Mill / galvanized" }, { label: "Origin", value: "GCC / EU" }],
    phone: "+974 55 345 6789", whatsapp: "+974 55 345 6789",
    email: "sales@qatarsteeltrading.example", verified: true,
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1200&q=85",
    posted: "Today",
  },
  {
    slug: "aac-blocks-project-supply",
    name: "AAC Blocks for Project Supply",
    materialGroup: "Construction Materials", materialType: "Blocks & Masonry",
    materialTypeSlug: "blocks-masonry", listingType: "Buyer",
    country: "UAE", countryCode: "AE", city: "Abu Dhabi", citySlug: "abu-dhabi",
    supplier: "Capital Build Procurement", priceRange: "Budget: AED 310,000",
    minimumOrder: "12,000 Blocks", availability: "Required within 21 days", leadTime: "Urgent",
    compliance: ["BS EN 771-4", "Civil Defence approved"],
    description: "Main contractor seeking approved AAC blocks for a residential development, including delivery to the Abu Dhabi project site.",
    specifications: [{ label: "Thickness", value: "100 / 150 / 200 mm" }, { label: "Density", value: "550–650 kg/m³" }, { label: "Quantity", value: "12,000 units" }, { label: "Delivery", value: "Abu Dhabi" }],
    phone: "+971 2 555 4010", whatsapp: "+971 50 555 4010",
    email: "buying@capitalbuild.example", verified: true,
    image: "https://images.unsplash.com/photo-1590074072786-a66914d668f1?auto=format&fit=crop&w=1200&q=85",
    posted: "1 day ago",
  },
  {
    slug: "hdpe-water-pipes",
    name: "HDPE Drainage & Water Pipes",
    materialGroup: "Industrial Materials", materialType: "Pipes & Valves",
    materialTypeSlug: "pipes-valves", listingType: "Supplier",
    country: "UAE", countryCode: "AE", city: "Dubai", citySlug: "dubai",
    supplier: "Al Wasl Piping Systems", priceRange: "AED 45–120 / Meter",
    minimumOrder: "1,000 Meters", availability: "In stock", leadTime: "5–7 working days",
    compliance: ["ISO 4427", "DIN 8074", "WRAS"],
    description: "Pressure and non-pressure HDPE pipes for municipal water, sewer drainage, and industrial chemical transport.",
    specifications: [{ label: "Diameter", value: "20–1200 mm" }, { label: "Pressure", value: "PN6–PN25" }, { label: "Material", value: "PE100" }, { label: "Jointing", value: "Butt / electrofusion" }],
    phone: "+971 50 987 6543", whatsapp: "+971 50 987 6543",
    email: "sales@alwaslpiping.example", verified: true,
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1200&q=85",
    posted: "3 days ago",
  },
  {
    slug: "galvanized-cable-trays",
    name: "Galvanized Cable Trays & Raceways",
    materialGroup: "Industrial Materials", materialType: "Electrical Supplies",
    materialTypeSlug: "electrical-supplies", listingType: "For Sale",
    country: "Bahrain", countryCode: "BH", city: "Manama", citySlug: "manama",
    supplier: "Bahrain Electro-Galvanizers", priceRange: "BHD 6–14 / Piece",
    minimumOrder: "100 Units", availability: "Made to order", leadTime: "7–10 working days",
    compliance: ["NEMA VE-1", "IEC 61537"],
    description: "Heavy-duty hot-dip galvanized cable trays, ladder racks, and custom raceways for commercial and industrial electrical routing.",
    specifications: [{ label: "Width", value: "50–900 mm" }, { label: "Thickness", value: "1.2–2.5 mm" }, { label: "Finish", value: "HDG / pre-galvanized" }, { label: "Length", value: "2.4 / 3 m" }],
    phone: "+973 39 123 456", whatsapp: "+973 39 123 456",
    email: "sales@beg.example", verified: false,
    image: "https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?auto=format&fit=crop&w=1200&q=85",
    posted: "5 days ago",
  },
  {
    slug: "industrial-air-filters",
    name: "Industrial HVAC Air Filters",
    materialGroup: "Industrial Materials", materialType: "HVAC Components",
    materialTypeSlug: "hvac-components", listingType: "Buyer",
    country: "Oman", countryCode: "OM", city: "Muscat", citySlug: "muscat",
    supplier: "Muscat Facilities Procurement", priceRange: "Budget: OMR 18,000",
    minimumOrder: "600 Units", availability: "Required monthly", leadTime: "Framework contract",
    compliance: ["EN 779", "ISO 16890"],
    description: "Facilities operator seeking a recurring supplier for pleated and bag filters for commercial and industrial HVAC systems.",
    specifications: [{ label: "Classes", value: "G4 / F7 / F9" }, { label: "Sizes", value: "Standard and custom" }, { label: "Quantity", value: "600 units/month" }, { label: "Contract", value: "12 months" }],
    phone: "+968 24 555 812", whatsapp: "+968 95 555 812",
    email: "procurement@muscatfacilities.example", verified: true,
    image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=1200&q=85",
    posted: "Yesterday",
  },
];

export const businessOpportunities: BusinessOpportunity[] = [
  {
    slug: "italian-restaurant-dubai-marina",
    title: "Profitable Italian Restaurant for Sale — Dubai Marina",
    section: "Businesses for Sale", category: "Restaurants",
    investment: "AED 1,200,000", country: "UAE", countryCode: "AE", city: "Dubai",
    postedDate: "10 Jul 2026", contact: "investments@dubaimarinabiz.example",
    phone: "+971 50 555 1234", whatsapp: "+971 50 555 1234",
    description: "Fully operating waterfront restaurant with 80 seats, professional kitchen, active licences, delivery partnerships, trained staff, and established monthly revenue.",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=900&q=80",
  },
  {
    slug: "wanted-specialty-cafe-riyadh",
    title: "Seeking Specialty Coffee Shop to Purchase — Riyadh",
    section: "Businesses Wanted", category: "Cafes",
    investment: "Budget: SAR 600,000", country: "Saudi Arabia", countryCode: "SA", city: "Riyadh",
    postedDate: "12 Jul 2026", contact: "acquisitions@riyadhcapital.example",
    phone: "+966 50 444 5678", whatsapp: "+966 50 444 5678",
    description: "Local investor seeking an established specialty café with active staff, supplier accounts, valid licences, and at least twelve months of stable revenue.",
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=900&q=80",
  },
  {
    slug: "metal-fabrication-equity-dammam",
    title: "Equity Partnership in Metal Fabrication Workshop",
    section: "Investment Opportunities", category: "Workshops",
    investment: "SAR 450,000 for 35% equity", country: "Saudi Arabia", countryCode: "SA", city: "Dammam",
    postedDate: "8 Jul 2026", contact: "partners@dammamsteel.example",
    phone: "+966 53 332 1987", whatsapp: "+966 53 332 1987",
    description: "Operating fabrication and welding workshop seeking growth capital for CNC machinery and laser cutting systems against a strong infrastructure-order backlog.",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=900&q=80",
  },
  {
    slug: "plastic-injection-factory-qatar",
    title: "Plastic Injection Moulding Factory for Acquisition",
    section: "Businesses for Sale", category: "Factories",
    investment: "QAR 4,800,000", country: "Qatar", countryCode: "QA", city: "Doha",
    postedDate: "6 Jul 2026", contact: "factory@qatarbrokerage.example",
    phone: "+974 4497 1234", whatsapp: "+974 4497 1234",
    description: "Fully equipped factory with six high-capacity moulding machines, experienced staff, long-term land lease, and active GCC export customers.",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=900&q=80",
  },
  {
    slug: "industrial-tools-company-bahrain",
    title: "Industrial Tools Trading Company for Sale — Manama",
    section: "Businesses for Sale", category: "Trading Companies",
    investment: "BHD 85,000", country: "Bahrain", countryCode: "BH", city: "Manama",
    postedDate: "11 Jul 2026", contact: "sale@bahrainindustrialtools.example",
    phone: "+973 1772 1234", whatsapp: "+973 1772 1234",
    description: "Profitable B2B trading company specialising in fasteners, safety wear, and power tools, with warehouse facilities and an established contractor client base.",
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=900&q=80",
  },
  {
    slug: "automated-car-wash-kuwait",
    title: "Automated Car Wash Center for Sale — Salmiya",
    section: "Businesses for Sale", category: "Car Washes",
    investment: "KWD 120,000", country: "Kuwait", countryCode: "KW", city: "Kuwait City",
    postedDate: "9 Jul 2026", contact: "sale@salmiyawash.example",
    phone: "+965 2461 2345", whatsapp: "+965 2461 2345",
    description: "High-volume automated car wash with water recycling, four detailing bays, customer lounge, documented EBITDA, and a secure long-term lease.",
    image: "https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?auto=format&fit=crop&w=900&q=80",
  },
  {
    slug: "wanted-electronics-shop-muscat",
    title: "Seeking Boutique Electronics Retail Shop — Muscat",
    section: "Businesses Wanted", category: "Retail Shops",
    investment: "Budget: OMR 30,000", country: "Oman", countryCode: "OM", city: "Muscat",
    postedDate: "13 Jul 2026", contact: "buyer@omanretail.example",
    phone: "+968 2452 5001", whatsapp: "+968 2452 5001",
    description: "Entrepreneur seeking a well-located retail shop specialising in smart-home electronics, mobile accessories, or gaming products.",
    image: "https://images.unsplash.com/photo-1534452203293-494d7ddbf7e0?auto=format&fit=crop&w=900&q=80",
  },
  {
    slug: "fast-food-franchise-riyadh",
    title: "International Fast Food Franchise Partner — Riyadh",
    section: "Investment Opportunities", category: "Franchise Businesses",
    investment: "SAR 1,800,000 setup", country: "Saudi Arabia", countryCode: "SA", city: "Riyadh",
    postedDate: "14 Jul 2026", contact: "franchise@gulfbrands.example",
    phone: "+966 11 401 3333", whatsapp: "+966 11 401 3333",
    description: "Master-franchise partnership for a growing European healthy fast-food brand with proven operations, training, and a pre-arranged supply chain.",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=900&q=80",
  },
];

export const projectTenders: ProjectTenderProfile[] = [
  {
    slug: "riyadh-commercial-tower-project",
    title: "Riyadh Commercial Tower Project",
    category: "projects-tenders",
    projectType: "Building Projects",
    projectTypes: ["building-projects"],
    country: "Saudi Arabia",
    countries: ["SA"],
    city: "Riyadh",
    cities: ["riyadh"],
    status: "Open for bidding",
    summary:
      "High-rise mixed-use commercial tower with premium façade and fit-out package.",
    description:
      "A landmark commercial development in Riyadh seeking experienced contractors for structural works, MEP coordination, and interior fit-out delivery.",
    budget: "SAR 220M",
    deadline: "15 Aug 2026",
    client: "Riyadh Development Authority",
    sectors: ["Commercial", "Mixed Use", "High-rise"],
    value: "SAR 220M",
    tenderType: "Open Tender",
    location: "Riyadh, Saudi Arabia",
    posted: "2 days ago",
    featured: true,
  },
  {
    slug: "al-rayyan-road-upgrade",
    title: "Al Rayyan Roads & Bridges Upgrade",
    category: "projects-tenders",
    projectType: "Roads & Bridges",
    projectTypes: ["roads-bridges"],
    country: "Qatar",
    countries: ["QA"],
    city: "Doha",
    cities: ["doha"],
    status: "Tender closing soon",
    summary:
      "Urban road and bridge enhancement project across high-traffic logistics corridors.",
    description:
      "The project includes bridge decks, road widening, lighting systems, drainage upgrades, and utility relocation across Al Rayyan corridor connections.",
    budget: "QAR 180M",
    deadline: "27 Jul 2026",
    client: "Ashghal",
    sectors: ["Infrastructure", "Roads", "Mobility"],
    value: "QAR 180M",
    tenderType: "Restricted Tender",
    location: "Doha, Qatar",
    posted: "5 days ago",
    featured: true,
  },
  {
    slug: "duqm-industrial-plant-maintenance",
    title: "Duqm Industrial Plant Maintenance Contract",
    category: "projects-tenders",
    projectType: "Maintenance Contracts",
    projectTypes: ["maintenance-contracts"],
    country: "Oman",
    countries: ["OM"],
    city: "Muscat",
    cities: ["muscat"],
    status: "Prequalification in progress",
    summary:
      "Preventive and corrective maintenance for industrial utilities and process equipment.",
    description:
      "Scope includes HVAC servicing, mechanical maintenance, instrumentation, shutdown planning, and reliability improvement across a major industrial site.",
    budget: "OMR 34M",
    deadline: "09 Aug 2026",
    client: "Duqm Industrial City",
    sectors: ["Maintenance", "Industrial", "Utilities"],
    value: "OMR 34M",
    tenderType: "Prequalification",
    location: "Duqm, Oman",
    posted: "1 week ago",
    featured: false,
  },
  {
    slug: "kuwait-mep-retrofit-programme",
    title: "Kuwait MEP Retrofit Programme",
    category: "projects-tenders",
    projectType: "MEP Projects",
    projectTypes: ["mep-projects"],
    country: "Kuwait",
    countries: ["KW"],
    city: "Kuwait City",
    cities: ["kuwait-city"],
    status: "Open for bidding",
    summary:
      "MEP upgrade programme for government buildings, including chillers, BMS, and electrical modernization.",
    description:
      "The contract covers energy efficiency upgrades, ventilation retrofits, smart controls, and commissioning for multiple public buildings.",
    budget: "KWD 42M",
    deadline: "03 Sep 2026",
    client: "Public Works Authority",
    sectors: ["Government", "MEP", "Energy Efficiency"],
    value: "KWD 42M",
    tenderType: "Competitive Tender",
    location: "Kuwait City, Kuwait",
    posted: "3 days ago",
    featured: true,
  },
];

export const contractors: ContractorProfile[] = [
  {
    slug: "al-rashid-trading-contracting-company",
    name: "Al-Rashid Trading & Contracting Company (RTCC)",
    category: "contractors",
    companyType: "Construction Company",
    primaryType: "Civil Contractors",
    contractorTypes: [
      "civil-contractors",
      "building-contractors",
      "infrastructure-contractors",
    ],
    country: "Saudi Arabia",
    countries: ["SA"],
    city: "Riyadh",
    cities: ["riyadh"],
    yearEstablished: 2004,
    employees: "100 - 250",
    website: "www.alrashidtrading.com",
    email: "info@alrashidtrading.com",
    phone: "+966 11 401 2222",
    whatsapp: "+966 11 401 2222",
    address: "Olaya District, Riyadh, Saudi Arabia",
    description:
      "Leading construction company providing end-to-end building and engineering solutions across residential, commercial, industrial and infrastructure sectors.",
    services: [
      "Infrastructure Development",
      "Commercial High-rise",
      "Civil Works",
      "Water Pipelines",
      "Road Construction",
      "Concrete Works",
      "Steel Structure Works",
      "Fit-Out Works",
      "Renovation Works",
      "Project Management",
    ],
    areasServed: ["Riyadh", "Jeddah", "Dammam", "Dubai", "Doha"],
    rating: 4.8,
    reviewCount: 38,
    verified: true,
    premium: false,
    memberSince: "Jan 2021",
    responseTime: "Within 24 Hours",
    projectsCompleted: 55,
    licenses: ["SA-CC-482910", "ISO 9001", "ASTM Compliance"],
    gallery: [
      "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1590069261209-f8e9b8642343?auto=format&fit=crop&w=400&q=80",
    ],
    featuredProjects: [
      {
        title: "Residential Building Project",
        location: "Dubai, UAE",
        status: "Completed",
      },
      {
        title: "Commercial Complex",
        location: "Sharjah, UAE",
        status: "Completed",
      },
      {
        title: "Infrastructure Development",
        location: "Abu Dhabi, UAE",
        status: "In Progress",
      },
    ],
  },
  {
    slug: "arabian-construction-company",
    name: "Arabian Construction Company (ACC)",
    category: "contractors",
    companyType: "Construction Company",
    primaryType: "Infrastructure Contractors",
    contractorTypes: [
      "infrastructure-contractors",
      "civil-contractors",
      "building-contractors",
    ],
    country: "UAE",
    countries: ["AE"],
    city: "Dubai",
    cities: ["dubai"],
    yearEstablished: 1975,
    employees: "500+",
    website: "www.accuae.com",
    email: "contact@accuae.com",
    phone: "+971 4 345 5555",
    whatsapp: "+971 4 345 5555",
    address: "Sheikh Zayed Road, Dubai, UAE",
    description:
      "A leading contracting group specializing in high-rise towers, airport terminals, smart-city infrastructure, and major oil and gas works.",
    services: [
      "High-rise Construction",
      "Oil & Gas Industrial",
      "Marine Works",
      "Piling & Foundations",
      "Roads & Bridges",
      "EPC Delivery",
    ],
    areasServed: ["Dubai", "Abu Dhabi", "Sharjah", "Doha", "Riyadh"],
    rating: 4.9,
    reviewCount: 52,
    verified: true,
    premium: true,
    memberSince: "May 2019",
    responseTime: "Within 12 Hours",
    projectsCompleted: 70,
    licenses: ["DUBAI-CC-9071", "ISO 14001", "ISO 45001"],
    gallery: [
      "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=400&q=80",
    ],
    featuredProjects: [
      {
        title: "Metro Terminal Upgrade",
        location: "Dubai, UAE",
        status: "In Progress",
      },
      {
        title: "Offshore Refurbishment",
        location: "Abu Dhabi, UAE",
        status: "Completed",
      },
      {
        title: "Smart City Roadworks",
        location: "Doha, Qatar",
        status: "Completed",
      },
    ],
  },
  {
    slug: "qatari-diar-infrastructure-services",
    name: "Qatari Diar Infrastructure Services",
    category: "contractors",
    companyType: "Construction Company",
    primaryType: "Infrastructure Contractors",
    contractorTypes: [
      "infrastructure-contractors",
      "civil-contractors",
      "building-contractors",
    ],
    country: "Qatar",
    countries: ["QA"],
    city: "Doha",
    cities: ["doha"],
    yearEstablished: 2012,
    employees: "200 - 500",
    website: "www.qatari-diar.com",
    email: "projects@qatari-diar.com",
    phone: "+974 44 97 1111",
    whatsapp: "+974 44 97 1111",
    address: "Lusail City, Doha, Qatar",
    description:
      "Committed to sustainable infrastructure development and large-scale urban growth in Qatar through high-quality engineering delivery.",
    services: [
      "Urban Development",
      "Roads & Bridges",
      "Landscaping",
      "Mechanical Services",
      "Utilities",
    ],
    areasServed: ["Doha", "Lusail", "Al Rayyan", "Riyadh"],
    rating: 4.7,
    reviewCount: 29,
    verified: true,
    premium: false,
    memberSince: "Sep 2020",
    responseTime: "Within 48 Hours",
    projectsCompleted: 85,
    licenses: ["QA-CC-1087", "QCS Compliance"],
    gallery: [
      "https://images.unsplash.com/photo-1590069261209-f8e9b8642343?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=400&q=80",
    ],
    featuredProjects: [
      {
        title: "Lusail City Roads",
        location: "Doha, Qatar",
        status: "Completed",
      },
      {
        title: "Qatar Rail Support",
        location: "Doha, Qatar",
        status: "In Progress",
      },
    ],
  },
  {
    slug: "galfar-engineering-contracting",
    name: "Galfar Engineering & Contracting",
    category: "contractors",
    companyType: "Construction Company",
    primaryType: "MEP Contractors",
    contractorTypes: [
      "mep-contractors",
      "electrical-contractors",
      "plumbing-contractors",
    ],
    country: "Oman",
    countries: ["OM"],
    city: "Muscat",
    cities: ["muscat"],
    yearEstablished: 1998,
    employees: "400+",
    website: "www.galfar.com",
    email: "enquiries@galfar.com",
    phone: "+968 24 525000",
    whatsapp: "+968 24 525000",
    address: "Ghala Industrial Area, Muscat, Oman",
    description:
      "Oman’s leading engineering and contracting company with a strong focus on oil and gas infrastructure, civil structures, and environmental engineering.",
    services: [
      "Oil & Gas Pipelines",
      "Roads & Bridges",
      "Water Treatment",
      "Electrical Transmission",
      "Fabrication",
    ],
    areasServed: ["Muscat", "Salalah", "Duqm", "Riyadh"],
    rating: 4.6,
    reviewCount: 41,
    verified: true,
    premium: true,
    memberSince: "Jun 2018",
    responseTime: "Within 24 Hours",
    projectsCompleted: 100,
    licenses: ["OM-CC-2024", "IEC Compliance"],
    gallery: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1590069261209-f8e9b8642343?auto=format&fit=crop&w=400&q=80",
    ],
    featuredProjects: [
      {
        title: "Water Treatment Plant",
        location: "Muscat, Oman",
        status: "Completed",
      },
      {
        title: "Pipeline Upgrade",
        location: "Duqm, Oman",
        status: "In Progress",
      },
    ],
  },
  {
    slug: "kharafi-national",
    name: "Kharafi National",
    category: "contractors",
    companyType: "Contracting Group",
    primaryType: "MEP Contractors",
    contractorTypes: [
      "mep-contractors",
      "electrical-contractors",
      "hvac-contractors",
    ],
    country: "Kuwait",
    countries: ["KW"],
    city: "Kuwait City",
    cities: ["kuwait-city"],
    yearEstablished: 2007,
    employees: "350",
    website: "www.kharafi.com",
    email: "operations@kharafi.com",
    phone: "+965 2461 2000",
    whatsapp: "+965 2461 2000",
    address: "Shuaiba Industrial Zone, Kuwait City, Kuwait",
    description:
      "Delivering diversified contracting, MEP, commissioning, and facilities management services for industrial and commercial clients.",
    services: [
      "MEP Contracting",
      "Facilities Management",
      "Fabrication",
      "Instrumentation",
      "Commissioning",
    ],
    areasServed: ["Kuwait City", "Ahmadi", "Jahra", "Dubai"],
    rating: 4.5,
    reviewCount: 34,
    verified: true,
    premium: false,
    memberSince: "Nov 2022",
    responseTime: "Within 36 Hours",
    projectsCompleted: 115,
    licenses: ["KW-CC-7641", "TUV Certified"],
    gallery: [
      "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=400&q=80",
    ],
    featuredProjects: [
      {
        title: "Industrial MEP Retrofit",
        location: "Ahmadi, Kuwait",
        status: "Completed",
      },
    ],
  },
  {
    slug: "nass-corporation",
    name: "Nass Corporation",
    category: "contractors",
    companyType: "Heavy Civil & Marine Contractor",
    primaryType: "Civil Contractors",
    contractorTypes: [
      "civil-contractors",
      "infrastructure-contractors",
      "building-contractors",
    ],
    country: "Bahrain",
    countries: ["BH"],
    city: "Manama",
    cities: ["manama"],
    yearEstablished: 2001,
    employees: "150 - 300",
    website: "www.nassbh.com",
    email: "sales@nassbh.com",
    phone: "+973 1772 5522",
    whatsapp: "+973 1772 5522",
    address: "Mina Salman Industrial Area, Manama, Bahrain",
    description:
      "Marine engineering, piling, precast concrete, works, and heavy machinery procurement specialists across the Gulf.",
    services: [
      "Marine Engineering",
      "Piling",
      "Precast Concrete",
      "Heavy Machinery Supply",
      "Logistics",
    ],
    areasServed: ["Manama", "Mina Salman", "Doha", "Dubai"],
    rating: 4.7,
    reviewCount: 22,
    verified: true,
    premium: false,
    memberSince: "Jan 2023",
    responseTime: "Within 24 Hours",
    projectsCompleted: 130,
    licenses: ["BH-CC-4401", "Marine Safety"],
    gallery: [
      "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=400&q=80",
    ],
    featuredProjects: [
      {
        title: "Marine Jetty Works",
        location: "Manama, Bahrain",
        status: "Completed",
      },
    ],
  },
];
