const docs=window.DOCS;const nav=document.querySelector('#navigation');const content=document.querySelector('#content');const toc=document.querySelector('#pageToc');const crumbs=document.querySelector('#breadcrumbs');const prev=document.querySelector('#previousPage');const next=document.querySelector('#nextPage');const search=document.querySelector('#searchInput');const results=document.querySelector('#searchResults');const sidebar=document.querySelector('#sidebar');const menu=document.querySelector('#menuButton');const backdrop=document.querySelector('#backdrop');
const flat=docs.flatMap((page)=>page.sections.map((section)=>({page,section,text:[page.title,page.lead,section.title,JSON.stringify(section)].join(' ').toLowerCase()})));
function esc(value){return String(value).replace(/[&<>'"]/g,(x)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[x]))}
function route(){const parts=location.hash.replace(/^#\/?/,'').split('/').filter(Boolean);const page=docs.find((x)=>x.id===parts[0])||docs[0];const section=page.sections.find((x)=>x.id===parts[1])||page.sections[0];return{page,section}}
function renderNav(activePage,activeSection){nav.innerHTML=docs.map((page)=>`<div class="nav-group ${page.id===activePage.id?'open':''}"><button class="nav-group-button ${page.id===activePage.id?'active':''}" data-group="${page.id}" aria-expanded="${page.id===activePage.id}"><span class="nav-icon">${page.icon}</span><span>${esc(page.title)}</span><span class="nav-chevron">›</span></button><div class="nav-children">${page.sections.map((s)=>`<a class="nav-child ${page.id===activePage.id&&s.id===activeSection.id?'active':''}" href="#/${page.id}/${s.id}">${esc(s.title)}</a>`).join('')}</div></div>`).join('');nav.querySelectorAll('[data-group]').forEach((button)=>button.addEventListener('click',()=>{const group=button.parentElement;group.classList.toggle('open');button.setAttribute('aria-expanded',group.classList.contains('open'))}))}
function table(rows){return `<div class="doc-table-wrap"><table class="doc-table"><thead><tr><th>Item</th><th>Behaviour / details</th></tr></thead><tbody>${rows.map(([a,b])=>`<tr><td>${esc(a)}</td><td>${esc(b)}</td></tr>`).join('')}</tbody></table></div>`}
function renderSection(s){let html='';if(s.body)html+=s.body.map((p)=>`<p>${esc(p)}</p>`).join('');if(s.table)html+=table(s.table);if(s.steps)html+=`<div class="steps">${s.steps.map(([a,b])=>`<div class="step"><strong>${esc(a)}</strong>${esc(b)}</div>`).join('')}</div>`;if(s.permissions)html+=`<div class="permission-grid">${s.permissions.map(([a,b])=>`<div class="permission"><span>${esc(a)}</span><div>${esc(b)}</div></div>`).join('')}</div>`;if(s.callout)html+=`<div class="callout ${s.callout[0].toLowerCase().includes('important')||s.callout[0].toLowerCase().includes('privacy')?'warning':''}"><strong>${esc(s.callout[0])}:</strong> ${esc(s.callout[1])}</div>`;if(s.links)html+=`<ul>${s.links.map(([a,b])=>`<li><a href="${b}">${esc(a)} →</a></li>`).join('')}</ul>`;return html}
function render(){const {page,section}=route();document.title=`${page.title} — GulfInfraHub Documentation`;renderNav(page,section);crumbs.innerHTML=`<a href="#/introduction/overview">Documentation</a> <span>›</span> ${esc(page.title)}`;content.innerHTML=`<div id="top"></div><div class="eyebrow">${esc(page.title)} documentation</div><h1>${esc(page.title)}</h1><p class="lead">${esc(page.lead)}</p>${page.sections.map((s)=>`<section id="${s.id}"><h2><a href="#/${page.id}/${s.id}">${esc(s.title)}</a></h2>${renderSection(s)}</section>`).join('')}`;content.querySelectorAll('h2 a').forEach((a)=>{a.style.color='inherit';a.style.textDecoration='none'});toc.innerHTML=page.sections.map((s)=>`<a href="#/${page.id}/${s.id}" class="${s.id===section.id?'active':''}">${esc(s.title)}</a>`).join('');const pidx=flat.findIndex((x)=>x.page.id===page.id&&x.section.id===section.id);setPager(prev,flat[pidx-1],'Previous');setPager(next,flat[pidx+1],'Next');requestAnimationFrame(()=>{const target=document.getElementById(section.id);if(target)target.scrollIntoView({block:'start'});document.querySelector('#main').focus({preventScroll:true})});closeSidebar()}
function setPager(el,item,label){if(!item){el.innerHTML='';el.removeAttribute('href');return}el.href=`#/${item.page.id}/${item.section.id}`;el.innerHTML=`<small>${label}</small>${esc(item.page.title)} — ${esc(item.section.title)}`}
function doSearch(){const q=search.value.trim().toLowerCase();if(!q){results.hidden=true;results.innerHTML='';return}const hits=flat.filter((x)=>x.text.includes(q)).slice(0,10);results.innerHTML=hits.length?hits.map((x)=>`<a class="search-result" href="#/${x.page.id}/${x.section.id}"><strong>${esc(x.section.title)}</strong><small>${esc(x.page.title)}</small></a>`).join(''):`<div class="search-result"><strong>No matching documentation</strong><small>Try a shorter feature or module name.</small></div>`;results.hidden=false}
function closeSidebar(){sidebar.classList.remove('open');backdrop.hidden=true;menu.setAttribute('aria-expanded','false')}
search.addEventListener('input',doSearch);search.addEventListener('keydown',(e)=>{if(e.key==='Escape'){results.hidden=true;search.blur()}});document.addEventListener('keydown',(e)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();search.focus();doSearch()}});document.addEventListener('click',(e)=>{if(!e.target.closest('.global-search'))results.hidden=true});menu.addEventListener('click',()=>{const opening=!sidebar.classList.contains('open');sidebar.classList.toggle('open',opening);backdrop.hidden=!opening;menu.setAttribute('aria-expanded',String(opening))});backdrop.addEventListener('click',closeSidebar);window.addEventListener('hashchange',render);if(!location.hash)location.hash='#/introduction/overview';else render();
