from pathlib import Path
from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_CELL_VERTICAL_ALIGNMENT
from docx.shared import Inches, Pt, RGBColor
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/"deliverables"
NAVY,BLUE,AMBER,INK,MUTED,LIGHT,PALE_BLUE,PALE_AMBER,WHITE="0B1F3A","1D4ED8","F4B400","162235","64748B","E8EEF5","EAF2FF","FFF7D6","FFFFFF"

def font(r,size=11,bold=False,color=INK):
    r.font.name="Calibri"; r._element.get_or_add_rPr().rFonts.set(qn("w:ascii"),"Calibri"); r._element.get_or_add_rPr().rFonts.set(qn("w:hAnsi"),"Calibri"); r.font.size=Pt(size); r.bold=bold; r.font.color.rgb=RGBColor.from_string(color)
def shade(c,fill):
    pr=c._tc.get_or_add_tcPr(); n=pr.find(qn("w:shd"));
    if n is None: n=OxmlElement("w:shd"); pr.append(n)
    n.set(qn("w:fill"),fill)
def geometry(t,widths):
    t.autofit=False; pr=t._tbl.tblPr
    for tag,val in (("tblW",sum(widths)),("tblInd",120)):
        n=pr.find(qn(f"w:{tag}"));
        if n is None: n=OxmlElement(f"w:{tag}"); pr.append(n)
        n.set(qn("w:w"),str(val)); n.set(qn("w:type"),"dxa")
    g=t._tbl.tblGrid
    for x in list(g): g.remove(x)
    for width in widths: n=OxmlElement("w:gridCol"); n.set(qn("w:w"),str(width)); g.append(n)
    for row in t.rows:
        for i,c in enumerate(row.cells):
            pr=c._tc.get_or_add_tcPr(); n=pr.find(qn("w:tcW"));
            if n is None: n=OxmlElement("w:tcW"); pr.append(n)
            n.set(qn("w:w"),str(widths[i])); n.set(qn("w:type"),"dxa")
            mar=pr.first_child_found_in("w:tcMar")
            if mar is None: mar=OxmlElement("w:tcMar"); pr.append(mar)
            for side,val in (("top",80),("start",120),("bottom",80),("end",120)):
                x=mar.find(qn(f"w:{side}"));
                if x is None: x=OxmlElement(f"w:{side}"); mar.append(x)
                x.set(qn("w:w"),str(val)); x.set(qn("w:type"),"dxa")
            c.vertical_alignment=WD_CELL_VERTICAL_ALIGNMENT.CENTER
def para(d,text,size=11,bold=False,color=INK,after=6,align=None):
    p=d.add_paragraph(); p.paragraph_format.space_after=Pt(after); p.paragraph_format.line_spacing=1.25
    if align is not None:p.alignment=align
    font(p.add_run(text),size,bold,color)
def heading(d,text,level=1): p=d.add_paragraph(style=f"Heading {level}"); p.paragraph_format.keep_with_next=True; p.add_run(text)
def bullet(d,title,detail=""):
    p=d.add_paragraph(style="List Bullet"); p.paragraph_format.space_after=Pt(4); p.paragraph_format.line_spacing=1.25; font(p.add_run(title+(" — " if detail else "")),11,True,NAVY)
    if detail:font(p.add_run(detail))
def grid(d,rows,header=("Item","Behaviour"),widths=(2600,6760)):
    t=d.add_table(rows=0,cols=2); t.style="Table Grid"; cs=t.add_row().cells
    for i,x in enumerate(header):shade(cs[i],NAVY);font(cs[i].paragraphs[0].add_run(x),10,True,WHITE)
    for a,b in rows:
        cs=t.add_row().cells;shade(cs[0],LIGHT);font(cs[0].paragraphs[0].add_run(a),10,True,NAVY);font(cs[1].paragraphs[0].add_run(b),10)
        for c in cs:c.paragraphs[0].paragraph_format.space_after=Pt(0)
    geometry(t,list(widths));d.add_paragraph().paragraph_format.space_after=Pt(1)
def callout(d,label,text,amber=False):
    t=d.add_table(rows=1,cols=1);t.style="Table Grid";geometry(t,[9360]);c=t.cell(0,0);shade(c,PALE_AMBER if amber else PALE_BLUE);p=c.paragraphs[0];p.paragraph_format.space_after=Pt(0);font(p.add_run(label+": "),10.5,True,NAVY);font(p.add_run(text),10.5);d.add_paragraph().paragraph_format.space_after=Pt(1)
def page_no(p):
    r=p.add_run();a,s,e=(OxmlElement("w:fldChar") for _ in range(3));a.set(qn("w:fldCharType"),"begin");s.set(qn("w:fldCharType"),"separate");e.set(qn("w:fldCharType"),"end");i=OxmlElement("w:instrText");i.set(qn("xml:space"),"preserve");i.text=" PAGE ";v=OxmlElement("w:t");v.text="1"
    for n in (a,i,s,v,e):r._r.append(n)
    font(r,8.5,color=MUTED)
def base(title,subtitle):
    d=Document();sec=d.sections[0];sec.page_width,sec.page_height=Inches(8.5),Inches(11);sec.top_margin=sec.bottom_margin=sec.left_margin=sec.right_margin=Inches(1);sec.header_distance=sec.footer_distance=Inches(.492)
    n=d.styles["Normal"];n.font.name="Calibri";n.font.size=Pt(11);n._element.rPr.rFonts.set(qn("w:ascii"),"Calibri");n._element.rPr.rFonts.set(qn("w:hAnsi"),"Calibri");n.font.color.rgb=RGBColor.from_string(INK);n.paragraph_format.space_after=Pt(6);n.paragraph_format.line_spacing=1.25
    for name,size,color,before,after in (("Heading 1",16,BLUE,18,10),("Heading 2",13,BLUE,14,7),("Heading 3",12,"1F4D78",10,5)):
        s=d.styles[name];s.font.name="Calibri";s.font.size=Pt(size);s.font.bold=True;s.font.color.rgb=RGBColor.from_string(color);s._element.rPr.rFonts.set(qn("w:ascii"),"Calibri");s._element.rPr.rFonts.set(qn("w:hAnsi"),"Calibri");s.paragraph_format.space_before=Pt(before);s.paragraph_format.space_after=Pt(after);s.paragraph_format.keep_with_next=True
    lb=d.styles["List Bullet"];lb.font.name="Calibri";lb.font.size=Pt(11);lb.paragraph_format.left_indent=Inches(.375);lb.paragraph_format.first_line_indent=Inches(-.188);lb.paragraph_format.space_after=Pt(4);lb.paragraph_format.line_spacing=1.25
    h=sec.header.paragraphs[0];h.alignment=WD_ALIGN_PARAGRAPH.RIGHT;font(h.add_run(f"GulfInfraHub  |  {title}"),8.5,True,MUTED);f=sec.footer.paragraphs[0];f.alignment=WD_ALIGN_PARAGRAPH.RIGHT;font(f.add_run("Client reference  •  August 2026  |  "),8.5,color=MUTED);page_no(f)
    para(d,"CLIENT REFERENCE",10,True,AMBER,18,WD_ALIGN_PARAGRAPH.CENTER);para(d,title,28,True,NAVY,4,WD_ALIGN_PARAGRAPH.CENTER);para(d,subtitle,15,color=BLUE,after=18,align=WD_ALIGN_PARAGRAPH.CENTER);return d
def save(d,name):
    # Remove layout-only trailing paragraphs after a final table; Pages can push
    # these onto an otherwise blank last page.
    while d.paragraphs and not d.paragraphs[-1].text.strip():
        p=d.paragraphs[-1]._element;p.getparent().remove(p)
    OUT.mkdir(exist_ok=True);p=OUT/name;d.save(p);print(p)

def common_directory(title,scope,search,filters,card,detail,create,actions,security,filename):
    d=base(f"{title} Feature Guide",scope);callout(d,"Purpose",f"Explain how users discover, evaluate, save, contact and publish {title.lower()} records in the implemented application.")
    heading(d,"1. Entry points and page purpose");grid(d,[("Header menu",f"{title} opens the public directory."),("Homepage",f"Featured/latest cards and Browse All lead into {title}."),("Directory hero","Breadcrumb, module description, keyword, Category, Country and City controls."),("Primary CTA",create[0][0]+" opens Add Listing with the relevant module selected."),("Public access","Visitors may browse published records; protected actions request authentication.")])
    heading(d,"2. Directory search and filters");para(d,search);grid(d,filters,header=("Control","Matching behaviour"));callout(d,"Filter relationship","All active conditions must match. Leaving a control empty keeps that dimension unrestricted.")
    heading(d,"3. Listing cards and result actions");grid(d,card,header=("Card element","Displayed information or action"));bullet(d,"No results","The directory shows a module-specific no-match message and asks the user to adjust or clear criteria.")
    heading(d,"4. Detail page");grid(d,detail,header=("Section","Information or action"));
    heading(d,"5. Saving and contacting");grid(d,actions);callout(d,"Saved listings","Saving requires sign-in. The record is stored against the user and is available from Saved Listings; the same control can remove it.")
    heading(d,"6. Publishing a listing");para(d,"Publishing uses the standard four-stage Add Listing workflow: select type, enter details, add media/documents, then review and publish after fresh email OTP verification.");grid(d,create,header=("Creation area","Principal fields or rule"))
    heading(d,"7. Ownership, moderation and security");grid(d,security);bullet(d,"Owner management","The signed-in owner can access the record in My Listings, edit it and delete it.");bullet(d,"Edit moderation","Saving changes returns a standard listing to Pending for administrator review.");bullet(d,"Administrator","May approve, hold, reject and—after publication—feature eligible standard listings.");callout(d,"Blocked account","An administrator-blocked account cannot create, edit, save/contact through protected workflows, or publish listings.",True)
    heading(d,"8. Client acceptance checklist");
    for a,b in (("Discovery","Test keyword, country/city and all module filters."),("Record review","Open a card and verify every detail section and document/contact action."),("Account action","Save/unsave with signed-out and signed-in users."),("Creation","Validate required fields, media limits, OTP and Pending moderation state."),("Ownership","Verify only the owner can edit/delete and that non-published records are not publicly discoverable.")):bullet(d,a,b)
    save(d,filename)

common_directory("Contractors","Contractor directory, verified profiles and service-provider publishing","Keyword matching is case-insensitive across contractor name, company type, description, services, city and country.",[("Keyword","Search contractors or services."),("Contractor Type","Multi-select specializations."),("Country","Multi-select GCC countries; URL country filters can preselect values."),("City","Multi-select supported cities."),("Established since","Minimum establishment year; Any year disables this restriction."),("Reset","Clears the directory filters.")],[("Identity","Logo, name, company type and verification/premium indicators."),("Profile summary","Country, city, establishment year, description, services and rating/project metadata."),("Save","Adds/removes the contractor from Saved Listings."),("View Profile","Opens the contractor detail page.")],[("Overview","Verification status, company type, location, years active and completed-project metrics."),("About / Services","Company description and offered services."),("Company details","Business type, establishment year, main office, phone, website and email."),("Areas served","Countries/cities covered."),("Featured projects","Related project cards where available."),("Contact","Phone, email and WhatsApp actions; trust information is displayed alongside.")],[("Add Contractor Listing","Choose Contractors & Services."),("Business profile","Name, company type, year, workforce, specializations, services and licence."),("Location / contact","Country, city, address, service areas, email, phone, WhatsApp and website."),("Description / metrics","80–1,500-character description, completed projects and response-time information."),("Media","Logo URL, up to six gallery URLs and up to five named supporting-document URLs.")],[("Contact contractor","Use displayed phone/email/WhatsApp or the Contact destination."),("Website","Opens the contractor’s external site when supplied.")],[("Public scope","Only Published contractors appear in the directory."),("Verification badge","Represents marketplace verification data stored on the profile."),("Featured","Administrator-featured published profiles receive priority exposure.")],"GulfInfraHub_Contractors_Feature_Guide.docx")

common_directory("Projects & Tenders","Project discovery, tender participation and owner/applicant workflows","Keyword matching is case-insensitive across title, client, description, project/tender types, country and city.",[("Keyword","Search projects or clients."),("Project Type","Multi-select project/tender classifications."),("Country","Multi-select GCC countries."),("City","Multi-select supported cities."),("Directory hero","Keyword, Category, Country and dependent City can launch a filtered result URL."),("Reset","Clears local filters.")],[("Identity","Image, project/tender type, title and status."),("Context","Client, country, city, location and summary."),("Commercial","Budget/value and deadline."),("Save","Adds/removes the opportunity from Saved Listings."),("View more","Opens full tender/project detail.")],[("Opportunity summary","Title, status, location, capital value, bid deadline and reference."),("About","Summary and full description."),("Tender specifications","Value/budget, deadline, client/issuer, type and verification status."),("Bidding requirements","Standard eligibility/reminder checklist."),("Actions","Apply for this project and Request tender documents."),("Issuer information","Organization, submission location and reference."),("Documents","Project images and tender documents where supplied.")],[("Post Your Project","Choose Projects & Tenders."),("Project data","Title, project/tender types, status, summary/description, budget/value, deadline, client and tender type."),("Location","Country/city and sector/location information."),("Media","Up to six image URLs and up to five named tender-document URLs."),("Publication","Fresh OTP, ownership assignment and Pending moderation.")],[("Apply","Requires a verified, active account; owners cannot apply to their own project."),("Application fields","Company, contact person/email/phone, proposed role, 30–3,000-character cover message and optional HTTPS document URL."),("Application lifecycle","Submitted → Under Review / Shortlisted → Accepted or Rejected; applicant may withdraw while active."),("Request documents","Routes the user to the contact/support mechanism for BOQ and drawings.")],[("Uniqueness","One application per applicant per project; a Submitted application may be updated/resubmitted."),("Owner review","Only the project owner can review an application."),("Event history","Submission, review and withdrawal actions create timeline events.")],"GulfInfraHub_Projects_Tenders_Feature_Guide.docx")

common_directory("Equipment Marketplace","Heavy-equipment sale, rental and wanted-listing workflows","Keyword matching covers title, equipment type, brand, model, description, seller, location, city and country.",[("Keyword","Search brand, model or equipment."),("Listing Type","For Sale, For Rent or Wanted."),("Equipment Type","Multi-select supported equipment categories."),("Condition","New, Excellent, Good or Used."),("Country","Multi-select GCC countries."),("Reset","Clears all active conditions.")],[("Identity","Image, listing type, condition, title and equipment category."),("Machine data","Year, brand/model, country, city and location."),("Commercial","Price/budget and price note."),("Save","Adds/removes the equipment listing from Saved Listings."),("View Details","Opens the equipment detail page.")],[("Hero","Listing purpose, title, price and media gallery."),("Summary","Price/budget, condition and verification status."),("Overview","Description and listing information."),("Specifications","Label/value technical specifications."),("Seller panel","Seller name/type, availability, listing purpose, condition and posted date."),("Contact","WhatsApp and other seller contact data.")],[("Post Equipment Listing","Choose Equipment Marketplace."),("Identity","Title, type, sale/rent/wanted purpose, condition, brand, model and valid year."),("Commercial / logistics","Price/budget, price note, availability, operating hours and location."),("Technical","80–2,000-character description and at least one Label: Value specification."),("Seller","Name/type, phone, WhatsApp and optional valid email."),("Media","One to eight valid image URLs and named inspection/service/registration/certificate document URLs.")],[("Contact seller/buyer","Use WhatsApp/contact data on the detail page."),("Purpose-aware labels","The interface identifies whether the record is For Sale, For Rent or Wanted.")],[("Public scope","Only Published equipment records appear publicly."),("Media validation","A primary/valid image set and valid document URLs are enforced."),("Year/hours","Year and operating hours receive numeric range validation.")],"GulfInfraHub_Equipment_Marketplace_Feature_Guide.docx")

common_directory("Construction & Industrial Materials","Material sourcing, supplier/buyer discovery and product publishing","Keyword matching covers material name/type, supplier, description, city and country.",[("Keyword","Search material or supplier."),("Listing Type","Supplier, Buyer or supported material role values."),("Construction Materials","Multi-select construction material types."),("Industrial Materials","Multi-select industrial material types."),("Country","Multi-select GCC countries."),("Directory hero","Keyword, Category, Country and dependent City launch the module URL.")],[("Identity","Primary image, name, material type/group and verified/featured indicators."),("Supplier/context","Supplier name and brief description."),("Commercial","Price range, minimum order, city and country."),("Save","Adds/removes the material from Saved Listings."),("View material","Opens the material detail page.")],[("Summary","Estimated price/rate, minimum order and availability."),("Technical specifications","Structured product/compliance values."),("Description","Full description and key highlights."),("Contact","Context changes between Contact supplier and Contact buyer."),("Supplier details","Supplier identity and marketplace-verification status."),("Media/documents","Product gallery and technical/compliance records where supplied.")],[("Post Material Listing","Choose Industrial Materials / Construction & Industrial Materials."),("Classification","Material group and valid type; the selected type must belong to the group."),("Commercial","Supplier/buyer role, price range, MOQ, availability and delivery lead time."),("Technical","Specifications, compliance and description."),("Contact/location","Supplier/buyer identity, country, city, phone, WhatsApp and optional email."),("Media","Required primary image, up to six gallery URLs and up to five named datasheet/certificate/test/catalogue URLs.")],[("Request price/contact","Uses the listing owner’s contact route and role-aware wording."),("Save","Requires login and can be reversed from the listing or Saved Listings.")],[("Group/type integrity","Construction and Industrial material types are validated against their group."),("Public scope","Only Published materials are publicly browsable."),("Verification","Stored supplier verification is displayed, while moderation controls publication.")],"GulfInfraHub_Materials_Feature_Guide.docx")

common_directory("Business Opportunities","Businesses for sale/wanted, investment and partnership discovery","Keyword matching covers title, description, category and city.",[("Keyword","Examples: restaurant, workshop or factory."),("Sections","Multi-select opportunity sections such as sale, wanted or investment/partnership."),("Categories","Multi-select supported business categories."),("Countries","Multi-select countries derived from current records."),("Directory hero","Keyword, Category, Country and City can launch the module URL.")],[("Identity","Image, category, title and city/country."),("Summary","Short opportunity description."),("Commercial","Capital requirement, investment or asking price."),("Save","Adds/removes the opportunity from Saved Listings."),("View Details","Opens the opportunity detail."),("Contact Seller","Opens the public contact route.")],[("Hero / summary","Section, category, title, location and investment/budget."),("About","Full opportunity description."),("Owner contact","Request further information and arrange a confidential discussion."),("Direct action","Phone, email and WhatsApp where supplied."),("Save","Available to signed-in users.")],[("Post Business Opportunity","Choose Business Opportunities."),("Classification","Opportunity section/category and title."),("Commercial","Investment, budget or asking price."),("Narrative","Business/opportunity description and intended transaction."),("Location/contact","Country, city, owner/contact information."),("Media","Business images and non-confidential supporting-document URLs.")],[("Contact Seller","Routes to the listing/contact workflow."),("WhatsApp","Uses the stored contact number when available."),("Confidentiality","The UI warns publishers not to attach confidential records.")],[("Public scope","Only Published opportunities appear in the directory."),("Owner control","Only the owner can edit/delete the listing."),("Moderation","Pending records require administrator approval before discovery.")],"GulfInfraHub_Business_Opportunities_Feature_Guide.docx")

def simple_guide(title,subtitle,filename,sections):
    d=base(title,subtitle);callout(d,"Purpose",sections.pop(0))
    for idx,(name,content) in enumerate(sections,1):
        heading(d,f"{idx}. {name}")
        if isinstance(content,str):para(d,content)
        elif content and isinstance(content[0],tuple):grid(d,content)
        else:
            for a,b in content:bullet(d,a,b)
    if filename == "GulfInfraHub_About_Us_Feature_Guide.docx":
        for table in d.tables:
            for row in table.rows:
                for cell in row.cells:
                    for p in cell.paragraphs:
                        p.paragraph_format.line_spacing=1.0
                        for run in p.runs: run.font.size=Pt(9.5)
    save(d,filename)

simple_guide("About Us Feature Guide","Corporate purpose, positioning and core-pillar content","GulfInfraHub_About_Us_Feature_Guide.docx",[
"Explain the client-facing information presented by the About Us header destination.",
("Page access and purpose",[("Header link","About Us opens /about without requiring sign-in."),("Page metadata","Identifies the page as About Us | GulfInfraHub and describes GCC construction/industrial connectivity."),("Audience","Buyers, contractors, suppliers, project owners, investors and business partners evaluating the platform.")]),
("Hero message",[("Positioning","Built for the Gulf."),("Identity","About GulfInfraHub."),("Timeline","Facilitating industrial connections and construction sourcing across GCC markets since 2026.")]),
("Our purpose",[("Problem addressed","Visibility problems in Gulf construction supply chains."),("Regional scope","Saudi Arabia, UAE, Qatar, Kuwait, Oman and Bahrain."),("Industry need","Regulatory data, pre-qualifications and dynamic quotation tools for heavy civil and industrial procurement."),("Platform response","Structured directories, tender publishing, RFQ routing and heavy-machinery catalogues in one platform."),("Intended outcome","Enable engineering decision-makers to audit credentials and discover partners faster.")]),
("Core corporate pillars",[("Compliance Verification","Work toward checking matching, active Commercial Registration records."),("RFQ Sourcing Velocity","Goal of reducing tender-pricing collection cycles from weeks to under 48 hours."),("Local GCC Expertise","Awareness of bidding thresholds, customs rules and country-specific construction specifications."),("Secure Communication","Matching interfaces for confidential commercial and engineering documents.")]),
("Client interpretation",[("Informational page","The page communicates platform purpose; it does not itself submit a listing or RFQ."),("Claims wording","Verification and speed statements are framed as working practices/goals in the implemented copy."),("Next actions","Users continue through header links to directories, RFQs, Add Listing or Contact Us.")])])

simple_guide("Contact Us Feature Guide","Public support enquiries and administrator handling","GulfInfraHub_Contact_Us_Feature_Guide.docx",[
"Document the public Contact Us form, validation, submission storage and administrative review route.",
("Entry points and supported enquiries",[("Header / footer","Contact Us opens /contact."),("Sign-in","Not required."),("Supported topics","Listings, RFQs, tenders, supplier registration, account access and GCC partnership opportunities."),("Response expectation","The team responds using the contact details submitted.")]),
("Form fields and validation",[("Full name","Required; 2–100 characters."),("Phone or WhatsApp","Required; 7–25 characters using digits, spaces, +, parentheses or hyphen."),("Email","Required valid format; normalized to lowercase; maximum 160 characters."),("Message","Required; 10–3,000 characters."),("Submit state","Button changes to Submitting and is disabled while processing.")]),
("Successful submission",[("Storage","Creates a ContactSubmission record with name, phone/WhatsApp, email and message."),("Confirmation","Displays Message received and “Thank you. Your message has been submitted.”"),("Admin refresh","Revalidates the administrator Contact Submissions page.")]),
("Administrator handling",[("Destination","Authorized administrators review submissions at /admin/contact-submissions."),("Privacy","Contact details and enquiry text are not exposed in a public directory."),("Failure feedback","Invalid values return a specific correction message without showing success.")]),
("User checklist",[("Identify yourself","Use a real full name and monitored email/phone."),("Describe the request","Mention the relevant listing, RFQ, tender, account or partnership context."),("Avoid secrets","Do not place passwords or unnecessary confidential material in the message."),("Confirm success","Wait for the Message received state before leaving.")])])

simple_guide("Login & Registration Feature Guide","Email OTP, password access, session and recovery workflows","GulfInfraHub_Login_Registration_Feature_Guide.docx",[
"Explain how visitors create an account, verify email, sign in, recover access and reach role-specific destinations.",
("Entry and redirect",[("Header link","Login / Register opens /login."),("Existing session","A signed-in user is redirected to /admin for an administrator or /my-listings for a standard user."),("Methods","Email verification code or existing password."),("New account","An email-first OTP flow creates the user record when necessary.")]),
("Email-code sign-in",[("Email","Must use a valid address."),("Rate limit","One code request per email/purpose per minute."),("Code","Four numeric digits."),("Expiry","10 minutes."),("Attempts","Five failed attempts require a new code."),("Success","Marks email verified, creates a session and continues to password creation for a new account.")]),
("Password registration and login",[("New password","At least eight characters with at least one letter and one number."),("Confirmation","Must exactly match."),("Password login","Existing users may switch to email/password; invalid credentials return a generic error."),("Destination","Administrator → /admin; standard user → /my-listings.")]),
("Password recovery",[("Forgot password","Login provides /forgot-password."),("Reset link","The user follows an emailed token to /reset-password."),("Invalid link","The reset page explicitly reports a missing/invalid token."),("New password","Uses the application’s password-strength and confirmation rules.")]),
("Session and security",[("Cookie","HTTP-only session cookie; Secure in production; SameSite Lax."),("Lifetime","30 days unless removed/expired."),("Storage","Only a hash of the random session token is stored."),("Logout","Deletes the server session, clears the cookie and returns to the homepage."),("Blocked accounts","Authentication may still identify the user, but protected business mutations enforce blocked-account restrictions.")]),
("Account destinations",[("My Listings","Owned marketplace listings."),("My RFQs / My Quotations","Buyer and supplier procurement workspaces."),("Saved Listings","Bookmarked marketplace records."),("Applications","Project/tender participation records."),("Admin","Role-restricted administration area.")])])

simple_guide("Add Listing Feature Guide","Listing selection, drafts, media, OTP publication and ownership","GulfInfraHub_Add_Listing_Feature_Guide.docx",[
"Provide a complete cross-module reference for the Add Listing header action and standard publishing workflow.",
("Entry and listing types",[("Header / homepage","Add Listing opens /add-listing."),("Contractors & Services","Company/service profile."),("Projects & Tenders","Project or bidding opportunity."),("Request for Quotation","Redirects to /rfqs?create=1 and uses the dedicated RFQ workflow."),("Equipment Marketplace","For Sale, For Rent or Wanted equipment."),("Industrial Materials","Construction/industrial supplier or buyer record."),("Business Opportunities","Sale, wanted, investment or partnership opportunity.")]),
("Standard four-stage workflow",[("1. Select type","Choose one marketplace classification."),("2. Listing details","Complete module-specific identity, commercial, technical, location and contact data; a private Draft is created."),("3. Media/documents","Add valid hosted image and document URLs within module limits."),("4. Review & publish","Review the summary, complete a fresh email OTP and submit for moderation.")]),
("Draft protection and validation",[("Temporary ownership","A random edit token protects an unsigned/private creation draft."),("Validation","Server actions re-check required fields, data ranges, location relationships, email/phone and URLs."),("Hosted links","The current forms use external URLs until cloud storage is configured."),("Blocked user","Cannot add or publish; restriction screen provides Contact Support."),("Failed validation","Keeps the draft and returns field-specific messages.")]),
("Publication authorization",[("Fresh OTP","Required before every standard new listing is published."),("Email","Must match the listing/contact email and verified signed-in account."),("Code rules","Four digits, one-minute request limit, 10-minute expiry and five-attempt ceiling."),("Ownership assignment","Successful publication removes the temporary token and assigns the verified user as owner."),("Initial public status","The listing moves to Pending, not immediately Published.")]),
("Moderation",[("Approve","Pending → Published."),("Hold","Pending/eligible record → On Hold."),("Reject","Pending/eligible record → Rejected."),("Feature","Published standard listings may be featured; RFQs are excluded."),("Public discovery","Only Published records appear in the relevant public directory/global search.")]),
("Post-submission management",[("My Listings","Shows records owned by the signed-in user."),("Edit","Owner-only; saving changes returns the listing to Pending."),("Delete","Owner-only; removes the record and associated saved references."),("Status tracking","Draft, Pending, Published, On Hold, Rejected and Closed are represented as applicable."),("RFQ exception","RFQs are managed in My RFQs and follow their own Draft/Published/Closed/Awarded lifecycle.")]),
("Module media limits",[("Contractor","Logo, up to six gallery images and up to five named documents."),("Project/Tender","Up to six images and up to five tender documents."),("Equipment","One to eight images plus inspection/service/registration/certificate documents."),("Material","Required primary image, up to six gallery images and up to five technical/compliance documents."),("Business","Business images and non-confidential supporting documents."),("RFQ","BOQ, drawings, specification and other document URLs in the dedicated RFQ form.")]),
("Publisher checklist",[("Accuracy","Confirm category, country/city, commercial values, dates and contacts."),("Authorization","Use only media/documents the publisher may distribute."),("OTP","Keep the listing email accessible during final review."),("Moderation","Check My Listings for Pending/Published/Hold/Rejected status."),("Public QA","After approval, open the detail page and verify media, documents and contact actions.")])])
